/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xbiltacsovemluppcflr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiaWx0YWNzb3ZlbWx1cHBjZmxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5MjUyNjksImV4cCI6MjA5MzUwMTI2OX0.wN08EoXeh28RtpaWuhSKraT173El-c-lY-9e7peyFd8"